---
- name: Ensure default directories exists
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  with_items:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/includes"

- name: Ensure /etc/nginx/conf.d/default.conf file is absent
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload_nginx

- name: Copy https.include config
  template:
    src: https.include.j2
    dest: /etc/nginx/includes/https.include
    owner: root
    group: root
    mode: 0644
  notify: reload_nginx

- name: Copy default config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload_nginx

- name: Generate selfsigned cert and key
  shell: "stat /etc/ssl/private/nginx-selfsigned.key || \
    openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt
    -batch"
  ignore_errors: true
  changed_when: false
  notify: reload_nginx

- name: Generate dhparam
  shell: "stat /etc/ssl/certs/dhparam.pem || \
    openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
  ignore_errors: true
  changed_when: false
  notify: reload_nginx

- name: Copy custom configs
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "templates/configs/*"
  notify: reload_nginx
