---
- name: Check if iptables is installed
  package_facts:
    manager: auto

- name: Allow nginx from external
  iptables:
    ip_version: "{{ item }}"
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
    state: "{{ 'present' if (nginx_configure_firewall | bool) else 'absent' }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "nginx from external"
  with_items: ["ipv4", "ipv6"]
  notify: save_iptables_rules
  when: "'iptables' in ansible_facts.packages"
