---
- name: Allow nginx from external
  iptables:
    chain: INPUT
    protocol: tcp
    source: "0.0.0.0/0"
    destination_ports:
      - "80"
      - "443"
    state: "{{ 'present' if (nginx_configure_firewall | bool) else 'absent' }}"
    ctstate: NEW
    jump: ACCEPT
    comment: "nginx from external"
  notify: save_iptables_rules
