---
- name: Allow nginx from external.
  iptables:
    chain: INPUT
    protocol: tcp
    source: "0.0.0.0/0"
    destination_ports:
      - "80"
      - "443"
    state: present
    ctstate: NEW
    jump: ACCEPT
    comment: nginx from external

- name: Save iptables state.
  shell: "service iptables save"
  when: ansible_os_family == 'RedHat'

- name: Save iptables state.
  community.general.iptables_state:
    ip_version: ipv4
    state: saved
    path: /etc/iptables/rules.v4
  when: ansible_os_family == 'Debian'
