---
- name: (Alpine Linux) Install logrotate
  community.general.apk:
    name: logrotate
  when: ansible_facts['os_family'] == 'Alpine'

- name: (Debian/Ubuntu) Install logrotate
  apt:
    name: logrotate
    state: present
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5
  when: ansible_facts['os_family'] == 'Debian'

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Install logrotate
  yum:
    name: logrotate
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: (SLES) Install Logrotate
  community.general.zypper:
    name: logrotate
    state: present
  when: ansible_facts['os_family'] == 'Suse'

- name: Create logrotate config
  template:
    src: logrotate/nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: "0644"
  notify: logrotate
